// ============================================================
// Recipe data. Every stage carries BASE quantities (at baseRiceKg).
// The calculator scales rice + water + flour by (target / base),
// and distributes nuruk by each stage's share of base nuruk.
// Sourced from Korean classical texts + reconstructions; see /sources.
// ============================================================

export type Stage = {
  name: string; // 밑술, 1차 덧술 …
  ko: string; // korean label for the seal column
  when: string; // "Day 0", "~Day 12", "1st 해일"
  rice: number; // kg of rice, at base scale
  riceType: "멥쌀" | "찹쌀" | "멥쌀+찹쌀";
  form: "죽" | "범벅" | "구멍떡" | "고두밥" | "백설기";
  formEn: string; // english gloss of the form
  water: number; // L, at base scale
  nuruk: number; // g, at base scale
  flour: number; // g 밀가루, at base scale
  note?: string;
};

export type Recipe = {
  id: string;
  name: string; // 오양주
  hanja: string; // 五釀酒
  roman: string; // Oyangju
  category: string; // "이양주 · two-brew"
  profile: string; // "Strong · Dry · Clean"
  tagline: string;
  stagesLabel: string; // "Five mashings · 밑술 + 4 덧술"
  abv: string;
  ferment: string; // temperature + duration headline
  baseRice: number; // kg — sum of stage rice
  nurukPct: string; // headline nuruk ratio
  waterNote: string;
  stages: Stage[];
  about: string[]; // history / context paragraphs
  taste: string[]; // tasting notes
  method: string[]; // technique bullets
  accent: "vermilion" | "indigo" | "ochre";
};

export const recipes: Recipe[] = [
  {
    id: "oyangju",
    name: "오양주",
    hanja: "五釀酒",
    roman: "Oyangju",
    category: "오양주 · five-brew",
    profile: "Strong · Dry · Clean",
    tagline: "Five mashings. The long road to a strong, clean wine.",
    stagesLabel: "Five mashings · 밑술 + 네 번의 덧술",
    abv: "≈ 14–17%",
    ferment: "23–25 °C, ~30–50 days + months of cold aging",
    baseRice: 5,
    nurukPct: "≈ 10% of grain, front-loaded",
    waterNote: "Total rice : water ≈ 1 : 1 (저가수 — low water, strong & clean)",
    accent: "vermilion",
    stages: [
      {
        name: "밑술",
        ko: "밑",
        when: "Day 0",
        rice: 1,
        riceType: "멥쌀",
        form: "죽",
        formEn: "thin porridge",
        water: 2.0,
        nuruk: 350,
        flour: 100,
        note: "Cool the 죽 fully (≤25 °C) before the nuruk — heat kills the yeast. Stir 2–3×/day for the first days to bloom a dense colony.",
      },
      {
        name: "1차 덧술",
        ko: "一",
        when: "~Day 3",
        rice: 1,
        riceType: "멥쌀",
        form: "범벅",
        formEn: "thick paste",
        water: 1.5,
        nuruk: 0,
        flour: 0,
        note: "Feed when the 밑술 bubbles hard and just begins to thin & lose sweetness.",
      },
      {
        name: "2차 덧술",
        ko: "二",
        when: "~Day 6",
        rice: 1,
        riceType: "멥쌀",
        form: "범벅",
        formEn: "thick paste",
        water: 1.0,
        nuruk: 150,
        flour: 0,
        note: "The remaining ~30% of the nuruk goes in here, not at the end.",
      },
      {
        name: "3차 덧술",
        ko: "三",
        when: "~Day 9",
        rice: 1,
        riceType: "찹쌀",
        form: "고두밥",
        formEn: "firm steamed rice",
        water: 0.5,
        nuruk: 0,
        flour: 0,
        note: "Switch to glutinous rice, steamed dry. Cool fully, then break it into the mash for 30+ min.",
      },
      {
        name: "4차 덧술",
        ko: "四",
        when: "~Day 12",
        rice: 1,
        riceType: "찹쌀",
        form: "고두밥",
        formEn: "firm steamed rice",
        water: 0,
        nuruk: 0,
        flour: 0,
        note: "The dry final charge drives the alcohol. After it goes in, stop opening the lid.",
      },
    ],
    about: [
      "오양주 — “five-brewed wine” — is the longest and most demanding of the 가양주, the home-brewed wines of Korea. One 밑술 (seed mash) is fed four separate times. Each feeding lays a near-finished wine on top of the last, so the yeast never drowns in sugar and the alcohol climbs higher and cleaner than any single- or double-brew can reach.",
      "Korean brewers are candid that a single canonical 오양주 was never cleanly transmitted; the method here is reconstructed from the craft logic of 삼양주 and 청주 brewing and from documented five-brew recipes — the 홍국 오양주 patent and, most tellingly, the commercial 천비향 (by 좋은술), a 밑술 + 네 번의 덧술 wine built over roughly nine months — about three months fermenting, then long cold aging — to ~16% as an 약주 (14% as 탁주). Multi-brew heirloom wines in the same spirit include 동파주 (東坡酒, after the poet 소동파) and 무릉도원주 (武陵桃源酒), though these run two- to four-brews rather than five.",
    ],
    taste: [
      "Dry to off-dry, deep and rounded, with a clean grain sweetness rather than sugar. The long cold aging draws out a soft, almost nutty 청주 character once the clear wine is drawn off the top.",
      "Drawn clear it is a 약주/청주; stir the lees back with water and it becomes 막걸리. Nothing is wasted.",
    ],
    method: [
      "Dense, slightly sour 밑술 first — the single biggest quality lever. A low pH from 젖산 is your steriliser.",
      "법제 the nuruk (3 days, sun by day, dew by night) and ideally 수곡 it (steep overnight, use the liquid) to erase 누룩취 and clarify.",
      "Forms run 죽 → 범벅 → 고두밥; water falls and grain rises every stage.",
      "Ferment cool and slow (≤26 °C), then cold-settle for 1–2 months and draw the clear wine off the top.",
    ],
  },
  {
    id: "samhaeju",
    name: "삼해주",
    hanja: "三亥酒",
    roman: "Samhaeju",
    category: "삼양주 · three-brew",
    profile: "Strong · Dry · Clean · Cold-aged",
    tagline: "The Seoul winter wine, brewed across three pig-days.",
    stagesLabel: "Three mashings · 밑술 + 두 번의 덧술 (each on a 해일)",
    abv: "≈ 15–18%",
    ferment: "COLD — 10–15 °C, ~100 days (the “백일주”, hundred-day wine)",
    baseRice: 9,
    nurukPct: "≈ 4–5% (low — for a clear, sake-pale wine)",
    waterNote: "Total rice : water ≈ 1 : 1; nuruk only in the 밑술",
    accent: "indigo",
    stages: [
      {
        name: "밑술",
        ko: "亥",
        when: "1st 해일 · Day 0",
        rice: 1,
        riceType: "멥쌀",
        form: "범벅",
        formEn: "thick paste",
        water: 2.0,
        nuruk: 400,
        flour: 100,
        note: "Use fine wheat nuruk (분곡) + a little flour for a clear, colourless body. Seal with hanji and set it somewhere cold (~10–13 °C).",
      },
      {
        name: "1차 덧술",
        ko: "二",
        when: "2nd 해일 · ~Day 36",
        rice: 3,
        riceType: "멥쌀",
        form: "구멍떡",
        formEn: "holed rice-cakes, boiled & mashed",
        water: 3.0,
        nuruk: 0,
        flour: 0,
        note: "The long gap to the next pig-day works because it is cold — yeast slow, contaminants blocked.",
      },
      {
        name: "2차 덧술",
        ko: "三",
        when: "3rd 해일 · ~Day 72",
        rice: 5,
        riceType: "멥쌀",
        form: "고두밥",
        formEn: "firm steamed rice",
        water: 4.0,
        nuruk: 0,
        flour: 0,
        note: "Steamed-grain final stage → clear wine and higher alcohol. Then the long cold run to ~100 days.",
      },
    ],
    about: [
      "삼해주 — “three-pig-day wine” — is among the most-documented wines in the entire Korean classical canon. It is named as early as the 동국이상국집 (1241, in one of 이규보’s poems) and its method is set down across the Joseon recipe books (산가요록, 음식디미방, 산림경제, 주방문, 양주방). The 밑술 is laid down on the first 해일 (亥日, pig-day) of the lunar first month and fed again on each successive pig-day — about 36 days (one lunar month) apart — so across the three pig-days it runs ~100 days, the “백일주.” A faster 12-day-interval version is the 작은 삼해주. It ferments through the dead of winter.",
      "It was the signature 명주 of old 한양 (Seoul), brewed by the thousand-jar at 마포 독막, and prized enough that Joseon officials petitioned to ban it for draining the capital’s rice. It survives today as Seoul Intangible Cultural Heritage No. 8. Also called 유서주 (柳絮酒), willow-catkin wine, because it is ready as the willows bud in spring.",
    ],
    taste: [
      "Soft, fragrant and surprisingly strong — the cold, slow ferment locks in rice sweetness and a delicate aroma while pushing the alcohol up. Drawn clear it is almost sake-pale, thanks to the bran-sieved 분곡 nuruk.",
      "Distilled once it becomes 삼해소주 (~45°), described by its master as smoother than whisky aged a decade.",
    ],
    method: [
      "Cold is the whole point. Hold 10–15 °C — a cellar, an unheated room, a wine fridge. Warm it and the 12-day schedule fails and it sours.",
      "Keep ~36-day intervals between feedings — one month apart (a quicker 12-day-gap 작은 삼해주 also exists); you don’t need the actual calendar pig-days.",
      "Low nuruk + 분곡 + a little 밀가루 → the clear, colourless, almost-sake body it is famous for.",
      "Forms run 범벅/죽 → 구멍떡 → 고두밥. End the cycle 버들개지 필 무렵 — when the willows bud.",
    ],
  },
  {
    id: "seoktanju",
    name: "석탄주",
    hanja: "惜呑酒",
    roman: "Seoktanju",
    category: "이양주 · two-brew",
    profile: "Sweet · Fragrant · Soft",
    tagline: "“A pity to swallow it.” The sweetest of the old wines.",
    stagesLabel: "Two mashings · 밑술 + 한 번의 덧술 (이양주)",
    abv: "≈ 11–15% · about twice the sugar of ordinary wine",
    ferment: "25 °C early then cool; 밑술 ~3–7 days (seasonal), ~7 more after the 덧술",
    baseRice: 6,
    nurukPct: "≈ 6–7%",
    waterNote: "Water-poor: no water added at the 덧술 → concentrated sweetness",
    accent: "ochre",
    stages: [
      {
        name: "밑술",
        ko: "惜",
        when: "Day 0",
        rice: 1,
        riceType: "멥쌀",
        form: "죽",
        formEn: "porridge from rice flour",
        water: 5.2,
        nuruk: 400,
        flour: 0,
        note: "Mill the 멥쌀, cook to a 죽, and — critically — cool to ≤25 °C before the nuruk. Hot 죽 kills the yeast and the whole brew fails.",
      },
      {
        name: "덧술",
        ko: "呑",
        when: "~Day 5–7",
        rice: 5,
        riceType: "찹쌀",
        form: "고두밥",
        formEn: "firm steamed glutinous rice",
        water: 0,
        nuruk: 0,
        flour: 0,
        note: "A big glutinous-rice charge and NO added water — this water-poverty is what concentrates the honeyed sweetness. Ferment ~7 days more.",
      },
    ],
    about: [
      "석탄주 — 惜呑酒, literally “begrudge-to-swallow wine.” The 한국민족문화대백과 explains the name plainly: 그 맛이 달고 향기로워 입에 머금고 차마 삼키기가 아깝다 — “so sweet and fragrant you hold it in your mouth, loath to swallow.” It is also written 석탄향 (惜呑香).",
      "The 한국민족문화대백과 lists its recipe across four old texts — the 임원경제지, 양주방, 음식방문 and 술방문. In 담양 창평 it has long been the 홍주 송씨 family’s ancestral rite-wine — said to have entered the household when a royal married in, carrying a palace recipe with him — and is bottled today as 하심당 (下心堂) by 송영종, a soft ~11% 약주.",
    ],
    taste: [
      "Intensely sweet — sources put its sugar near twice that of ordinary wine — yet only ~11–15% alcohol, so it drinks soft and round. A pronounced fruit aroma, often described as 매실 (green plum), from ethyl acetate and phenethyl alcohol thrown off by the cool ferment.",
      "The classic arc is sweet-meets-bitter: the early bitterness falls away over seven days and resolves into honeyed sweetness. Pairs with 송편, 한과, rich braises — and famously with 담양’s spicy 메기찜.",
    ],
    method: [
      "The defining trick: add no water at the 덧술. The mash stays dense, so the sugar never gets diluted.",
      "Watch the temperature without water to cool it — a no-water ferment can spike and spoil; keep it in hand.",
      "For the biggest fruit aroma, take it cool after the first week (≤15 °C) and let it age.",
      "As an 이양주 it yields both 청주 (clear, off the top) and 막걸리 (the lees with water) at once.",
    ],
  },
  {
    id: "yaksanchun",
    name: "약산춘",
    hanja: "藥山春",
    roman: "Yaksanchun",
    category: "이양주 · two-brew (춘 wine)",
    profile: "Strong · Dry · Clean · Aromatic",
    tagline: "The Seoul scholar’s spring wine — “fragrant and sharp.”",
    stagesLabel: "Two mashings · 밑술 + 한 번의 덧술",
    abv: "≈ 15–18% (estimated — no historical figure)",
    ferment: "Cold & long — laid in 정월, drawn early April",
    baseRice: 6,
    nurukPct: "≈ 4% (low), best as 수곡 / water-nuruk",
    waterNote: "All water in the 밑술, dry 고두밥 덧술; rice : water ≈ 1 : 1.3 — dryness from full attenuation, not low water",
    accent: "indigo",
    stages: [
      {
        name: "밑술",
        ko: "藥",
        when: "1st 해일 · Day 0",
        rice: 2,
        riceType: "멥쌀",
        form: "백설기",
        formEn: "steamed rice-flour cake",
        water: 7.8,
        nuruk: 240,
        flour: 0,
        note: "Steam a 백설기, break it up, and dissolve it with 수곡 (nuruk steeped in the water overnight, solids strained out) for a clean, low-funk base. All the water goes in here. Stir with a peach branch (동도지) — the traditional anti-souring trick.",
      },
      {
        name: "덧술",
        ko: "春",
        when: "late 2월 · ~Day 40",
        rice: 4,
        riceType: "멥쌀",
        form: "고두밥",
        formEn: "firm steamed rice",
        water: 0,
        nuruk: 0,
        flour: 0,
        note: "All 멥쌀, steamed dry, mixed in warm with NO added water — the water-poverty plus the long cold rest is what makes it strong and bone-dry.",
      },
    ],
    about: [
      "약산춘 — 藥山春 — was the prized spring wine of the 서성 (徐渻) family of 약현 (藥峴) in old Seoul, counted among the capital’s great 명주. The “춘 (春)” is a literary label for a prized, long-aged wine (cf. 호산춘, 노산춘); 약산춘 took its name from 서성’s house in 약현 (now 중림동).",
      "Recorded across the 증보산림경제, 임원경제지 and 규합총서, and reconstructed by 국순당 in 2009 from the 임원경제지 method. Built like a precise 이양주: an all-멥쌀 base set with water-nuruk, then a dry steamed-rice feeding with no added water, laid down in the first lunar month and drawn in early April.",
    ],
    taste: [
      "Classically described as 향기롭고 맵다 — “fragrant and sharp.” The sharpness is the dryness and alcohol; the all-멥쌀 grain and full attenuation leave almost no residual sugar. Substantial in body yet crisp and clean on the finish.",
      "A refined, food-friendly dry 약주 — the antithesis of the sweet 석탄주.",
    ],
    method: [
      "Use 수곡 (water-nuruk) and a low nuruk dose for a clean, pale, low-funk wine.",
      "Keep the 덧술 water-poor — that concentration is the whole point.",
      "Long, cold fermentation (정월 → 4월). Stir vigorously early with a peach branch to bloom the yeast and ward off souring.",
      "Draw the clear wine off the top after the long rest.",
    ],
  },
  {
    id: "baekhaju",
    name: "백하주",
    hanja: "白霞酒",
    roman: "Baekhaju",
    category: "이양주 · two-brew",
    profile: "Dry · Clean · Pale",
    tagline: "“White glow” — the classic clear, dry 약주.",
    stagesLabel: "Two mashings · 밑술 + 한 번의 덧술",
    abv: "≈ 13–16%",
    ferment: "Moderate (neither cold nor hot), short — ~7–8 days after the 덧술",
    baseRice: 6,
    nurukPct: "≈ 8%",
    waterNote: "High-water — rice : water ≈ 1 : 2 (a pale, light wine)",
    accent: "vermilion",
    stages: [
      {
        name: "밑술",
        ko: "白",
        when: "Day 0",
        rice: 2,
        riceType: "멥쌀",
        form: "범벅",
        formEn: "half-cooked paste",
        water: 3.9,
        nuruk: 300,
        flour: 0,
        note: "Make a 범벅 (rice flour scalded half-cooked with boiling water), cool, then mix in nuruk and a little active starter. Stir daily to bloom the yeast.",
      },
      {
        name: "덧술",
        ko: "霞",
        when: "~Day 4",
        rice: 4,
        riceType: "멥쌀",
        form: "고두밥",
        formEn: "firm steamed rice",
        water: 7.7,
        nuruk: 200,
        flour: 0,
        note: "Steam 멥쌀 to 고두밥, cool, mix in. Done in ~7–8 days — test with a lit paper wick: when it no longer goes out over the surface, it’s ready.",
      },
    ],
    about: [
      "백하주 — 白霞酒, “white-glow wine” (the 霞 is the rosy glow of sunset, not mist) — is one of the oldest and most representative clear 약주, also recorded as 방문주 (方文酒) and set down in the 고사촬요 as a two-brew (이양법). Modern makers such as 국순당 cite it (via 생쌀발효법) as the inspiration behind 백세주.",
      "Where most of the old wines lean glutinous and sweet, 백하주 is built on 멥쌀 with generous water for a pale, dry, clean result — an everyday refined wine rather than a celebratory sweet one.",
    ],
    taste: [
      "Pale and nearly transparent, light-bodied, distinctly dry and clean — the 멥쌀 base keeps residual sugar low. A gentle grain-and-nuruk aroma rather than fruit or honey.",
      "Quick to make and easy-drinking; the benchmark for a clean dry house 약주.",
    ],
    method: [
      "All 멥쌀, generous water — the recipe for dry rather than sweet.",
      "범벅 base for a fast, clean yeast bloom; 고두밥 feed for a clear finish.",
      "A short ferment — watch the lit-wick / bubbling cues rather than a calendar.",
      "Cold-settle and draw the clear, pale wine off the top.",
    ],
  },
  {
    id: "byeokhyangju",
    name: "벽향주",
    hanja: "碧香酒",
    roman: "Byeokhyangju",
    category: "이양주 · two-brew",
    profile: "Driest · Clean · Fragrant",
    tagline: "The Pyongyang clear wine — “less sweet than the rest.”",
    stagesLabel: "Two mashings · 밑술 + 한 번의 덧술",
    abv: "≈ 13–15%",
    ferment: "Cool–moderate; ~5–7 days to the 덧술, then ~3 weeks",
    baseRice: 6,
    nurukPct: "≈ 8%",
    waterNote: "rice : water ≈ 1 : 1.1",
    accent: "indigo",
    stages: [
      {
        name: "밑술",
        ko: "碧",
        when: "Day 0",
        rice: 2.5,
        riceType: "멥쌀",
        form: "죽",
        formEn: "porridge",
        water: 3.4,
        nuruk: 320,
        flour: 160,
        note: "Cook a 죽 from milled 멥쌀, cool fully, then mix in nuruk and a little flour. 5–7 days to vigorous fermentation.",
      },
      {
        name: "덧술",
        ko: "香",
        when: "~Day 6",
        rice: 3.5,
        riceType: "멥쌀",
        form: "고두밥",
        formEn: "firm steamed rice",
        water: 3.4,
        nuruk: 160,
        flour: 0,
        note: "Steam 멥쌀, cool, mix in. Then a long ~2-month rest to clarify and round out.",
      },
    ],
    about: [
      "벽향주 — 碧香酒, “jade-fragrance wine” — was a celebrated clear wine of 평양 (Pyongyang) and one of the most widely recorded refined 약주 in the classical canon: 산가요록, 수운잡방, 음식디미방, 증보산림경제 and more. It exists in both 이양주 and 삼양주 versions; the two-brew here follows the 산림경제 method (술밑 + one 덧술 after ~7 days), while the RDA’s 2010 reconstruction is a three-brew 삼양주.",
      "The all-멥쌀 build and full fermentation make it the driest and cleanest of the named clear wines. It is bottled today as 세종대왕어주 (장희도가, 15%), a 산가요록 reproduction that took the presidential prize at the 2019 우리술품평회.",
    ],
    taste: [
      "Korean sources single it out as 단맛이 적은 편 — “on the less-sweet side” — i.e. the most clearly dry of the famous clear wines. Clean, fragrant, soft on the throat. Lighter in strength (~13–15%) than the 춘 wines, so it trades a little power for finesse.",
      "Reconstructions land around 13–15% — versions vary, so judge by taste.",
    ],
    method: [
      "All 멥쌀, both stages, for the driest result.",
      "죽 base, 고두밥 feed — the standard dry-and-clean progression.",
      "A long, unhurried finish is where the clarity and refinement come from.",
      "Hold it cool–moderate; don’t over-water or it sours.",
    ],
  },
  {
    id: "hosanchun",
    name: "호산춘",
    hanja: "壺山春",
    roman: "Hosanchun",
    category: "삼양주 · three-brew (춘 wine)",
    profile: "Very Strong · Dry · Keeps for months",
    tagline: "The 여산 spring wine — it won’t turn for months.",
    stagesLabel: "Three mashings · 밑술 + 두 번의 덧술",
    abv: "High — a documented “strong wine”",
    ferment: "Temperate (neither cold nor hot); ~13-day intervals, then 2–3 months aging",
    baseRice: 9,
    nurukPct: "≈ 7%",
    waterNote: "rice : water ≈ 1 : 1 (강주 — strong)",
    accent: "ochre",
    stages: [
      {
        name: "밑술",
        ko: "壺",
        when: "Day 0",
        rice: 1.5,
        riceType: "멥쌀",
        form: "죽",
        formEn: "porridge from rice flour",
        water: 1.5,
        nuruk: 200,
        flour: 100,
        note: "멥쌀 throughout in the 산림경제 method as transcribed — that build is what makes it dry. Cook to 죽, cool, mix nuruk + flour.",
      },
      {
        name: "1차 덧술",
        ko: "山",
        when: "~Day 13",
        rice: 2.5,
        riceType: "멥쌀",
        form: "범벅",
        formEn: "thick paste",
        water: 2.5,
        nuruk: 200,
        flour: 0,
        note: "Feed when the base is fermenting hard.",
      },
      {
        name: "2차 덧술",
        ko: "春",
        when: "~Day 26",
        rice: 5,
        riceType: "멥쌀",
        form: "고두밥",
        formEn: "firm steamed rice",
        water: 5,
        nuruk: 200,
        flour: 50,
        note: "The big steamed-rice charge drives the strength. The 산림경제 recipe puts equal 가루누룩 (2되) in every charge. Then 2–3 months of aging — the documented version “doesn’t change for two or three months.”",
      },
    ],
    about: [
      "호산춘 — 壺山春 — is the old specialty wine of 여산 (礪山, now 익산 여산면), named for the town’s byname 호산(壺山) and its mountain 천호산; the “춘 (春)” marks a prized, refined wine, not a strength (“sealed-pot” is a folk reading). It appears in the 산림경제 and 주방문 as an all-멥쌀 three-brew — the method as transcribed — a 독한 술 (strong wine) that keeps two or three months without turning.",
      "Note: today’s commercial 문경 호산춘 is a different wine — spelled 湖山春, the 장수황씨 family 가양주 (경상북도 무형문화재 제18호), sweeter, with double glutinous rice and pine needles (a famous ~18% 약주). This recipe follows the older 여산 壺山春 삼양주 documentary version — built for dry strength.",
    ],
    taste: [
      "Strong and dry, built from 멥쌀 across all three stages with a roughly 1:1 water ratio. Full but clean, with the keeping-quality that made it a wine you could lay down — the classical note is that it holds for months.",
      "The modern 문경 version, by contrast, is sweeter and pine-scented; if you want sweet-and-strong, brew that, but this one is for dry power.",
    ],
    method: [
      "All 멥쌀, every stage — the surest route to dry.",
      "Three mashings at ~13-day intervals, kept temperate (neither cold nor hot).",
      "Roughly 1:1 water for strength without stalling.",
      "Age 2–3 months; it rewards patience and keeps well.",
    ],
  },
  {
    id: "gyodongbeopju",
    name: "교동법주",
    hanja: "校洞法酒",
    roman: "Gyodong Beopju",
    category: "이양주 · two-brew (heritage)",
    profile: "Strong · Clean · Balanced",
    tagline: "The Gyeongju Choi-family wine — a 350-year heirloom 청주.",
    stagesLabel: "Two mashings · 밑술 + 한 번의 덧술",
    abv: "≈ 16–18%",
    ferment: "~100 days, drawn with a 용수",
    baseRice: 6,
    nurukPct: "≈ 10% (estimated — undisclosed)",
    waterNote: "Glutinous & water-lean (exact ratio undisclosed by the family)",
    accent: "vermilion",
    stages: [
      {
        name: "밑술",
        ko: "校",
        when: "Day 0",
        rice: 1,
        riceType: "찹쌀",
        form: "죽",
        formEn: "porridge",
        water: 2.0,
        nuruk: 400,
        flour: 0,
        note: "Unusually, both stages use 찹쌀. Cook a 죽, cool, mix in ground nuruk; ~1 week. Traditionally built on well-water steeped with 구기자 (goji) root, boiled and cooled.",
      },
      {
        name: "덧술",
        ko: "洞",
        when: "~Day 7",
        rice: 5,
        riceType: "찹쌀",
        form: "고두밥",
        formEn: "firm steamed glutinous rice",
        water: 3.0,
        nuruk: 200,
        flour: 0,
        note: "Steam 찹쌀 to 고두밥, cool, fold into the base; ~1 week active, then sink a 용수 and draw the clear wine over ~100 days total.",
      },
    ],
    about: [
      "교동법주 — officially 경주교동법주 (慶州校洞法酒) — is the ancestral wine of the 최부자 (Choi) family of 교동, 경주, brewed by the same household for some 350 years (since 최국선, a 사옹원 참봉 under King Sukjong) and designated National Intangible Cultural Heritage No. 86-3. 법주 means “wine made by the method/rule.”",
      "It is a pure-grain 청주 with an unusual all-찹쌀 build at both stages, raised on the family’s own well-water steeped with goji root. It is not the supermarket “경주법주” (a Japanese-style sake) — that is a different drink entirely.",
    ],
    taste: [
      "Bright, clear, micro-yellow (미황색). Clean and strong at 16–18% (originally ~19°, lowered to meet liquor law), with a grain sweetness and a faint acidity held in fine balance — “strong and clean” rather than bone-dry. Almost no perceptible water or sourness.",
      "A winter wine — the family doesn’t brew it in summer. The benchmark for a strong, clean heritage 청주.",
    ],
    method: [
      "Both stages 찹쌀, water-lean, for a rich but clean strong wine.",
      "Build on mineral well-water (traditionally goji-root water), boiled and cooled.",
      "~100-day fermentation; draw the clear wine with a 용수 basket.",
      "Brew in the cold months only.",
    ],
  },
];
