// Merge all generated partition files in data/gen/*.json into words-data.js.
// Dedupes by (w|r), keeping the lowest JLPT level on collision.
// Usage: node tools/build-words.mjs
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const GEN = join(ROOT, 'data', 'gen');
const POS_ORDER = ['noun', 'verb', 'adjective', 'adverb', 'expression', 'other'];
const LVL_RANK = { N5: 0, N4: 1, N3: 2, N2: 3, N1: 4 };

const cp = (c) => c.codePointAt(0);
const isKanji = (c) => (cp(c) >= 0x4e00 && cp(c) <= 0x9fff) || (cp(c) >= 0x3400 && cp(c) <= 0x4dbf) || c === '々';
const isHira = (c) => cp(c) >= 0x3041 && cp(c) <= 0x309f;
const isKata = (c) => (cp(c) >= 0x30a1 && cp(c) <= 0x30fa) || c === 'ー' || c === '・' || c === 'ヴ';
const isKana = (c) => isHira(c) || isKata(c);
// Recompute the script tag from the written form (don't trust the generator).
function scriptOf(w) {
  const chars = [...w];
  if (chars.some(isKanji)) return 'kanji';
  if (chars.length && chars.every(isKata)) return 'katakana';
  return 'hiragana';
}
// Reading must be pure kana to be useful in a reading trainer.
const readingIsKana = (r) => [...r].length > 0 && [...r].every(isKana);

const files = readdirSync(GEN).filter((f) => f.endsWith('.json'));
if (!files.length) {
  console.error('No partition files in data/gen/. Run the generation agents first.');
  process.exit(1);
}

const byId = new Map();
let read = 0, skipped = 0;
for (const f of files) {
  let arr;
  try { arr = JSON.parse(readFileSync(join(GEN, f), 'utf8')); }
  catch (e) { console.error(`  ! ${f}: invalid JSON — ${e.message}`); continue; }
  if (!Array.isArray(arr)) { console.error(`  ! ${f}: not an array`); continue; }
  for (const e of arr) {
    read++;
    if (!e || typeof e !== 'object') { skipped++; continue; }
    const w = String(e.w || '').trim();
    const r = String(e.r || '').trim();
    const o = String(e.o || '').trim().toLowerCase();
    const m = String(e.m || '').trim();
    const lvl = String(e.lvl || '').trim();
    const pos = String(e.pos || '').trim();
    const s = String(e.s || '').trim();
    if (!w || !r || !o || !m || !(lvl in LVL_RANK) || !POS_ORDER.includes(pos)) { skipped++; continue; }
    if (!readingIsKana(r)) { skipped++; continue; }   // drop Latin/kanji readings (CD, Tシャツ, アメリカ人, …)
    const entry = { w, r, o, m, lvl, pos, s: scriptOf(w) };   // recompute script tag deterministically
    const id = w + '|' + r;
    const prev = byId.get(id);
    if (!prev || LVL_RANK[lvl] < LVL_RANK[prev.lvl]) byId.set(id, entry);
  }
}

const words = [...byId.values()].sort((a, b) =>
  (LVL_RANK[a.lvl] - LVL_RANK[b.lvl]) ||
  (POS_ORDER.indexOf(a.pos) - POS_ORDER.indexOf(b.pos)) ||
  a.w.localeCompare(b.w, 'ja')
);

const lines = words.map((e) =>
  `  { w:${JSON.stringify(e.w)}, r:${JSON.stringify(e.r)}, o:${JSON.stringify(e.o)}, ` +
  `m:${JSON.stringify(e.m)}, lvl:${JSON.stringify(e.lvl)}, pos:${JSON.stringify(e.pos)}, s:${JSON.stringify(e.s)} }`
);

const out = `// Vocabulary dataset for Words mode. Auto-generated by tools/build-words.mjs.
// Each entry: { w (written form), r (kana reading), o (romaji), m (meaning), lvl (JLPT), pos, s (script) }
// Do not edit by hand — re-run: npm run build-data && npm run validate
const WORD_POS_ORDER = ${JSON.stringify(POS_ORDER)};

const WORDS = [
${lines.join(',\n')}
];

if (typeof window !== 'undefined') { window.WORDS = WORDS; window.WORD_POS_ORDER = WORD_POS_ORDER; }
if (typeof module !== 'undefined' && module.exports) { module.exports = { WORDS, WORD_POS_ORDER }; }
`;

writeFileSync(join(ROOT, 'words-data.js'), out, 'utf8');
console.log(`Read ${read} raw, skipped ${skipped}, wrote ${words.length} unique entries to words-data.js`);
const byLvl = Object.keys(LVL_RANK).map((l) => `${l}:${words.filter((w) => w.lvl === l).length}`).join('  ');
const byScript = ['kanji', 'hiragana', 'katakana'].map((s) => `${s}:${words.filter((w) => w.s === s).length}`).join('  ');
const byPos = POS_ORDER.map((p) => `${p}:${words.filter((w) => w.pos === p).length}`).join('  ');
console.log('  level:', byLvl);
console.log('  script:', byScript);
console.log('  pos:', byPos);
